version: ~> 1.0

env:
  global:
    - secure: "yoUZPpg5aDgICUE3IShn4LWxKVvIjBQZjzfOlRms5HU7fKFQLYKaZFtoiiDRJNPg17TJMZMVZLqK9OacM0SiYg7R0XeOBr6A/V15lqaUqDbP2IMv/G3WoInYyjo/RrYaev6MN0oFQGbmdMfpNiyhSki8b3dLSqWhNakkmwZN1WNCW3WlXRb+bjw46wfMpmEU9GwY45ggatus4dhaAmp003agIzGLXSrgxXCd36eOxmzIIU0GZkeca57yt0xJjHIBcqVKjU730Dz5bLrv8H6oNL0i5GOXH9Wf8aE0kIsAAYqPGOqt0EP7ln0CRRa1sOexNqcby9fY29Za5gBne8uu51pAU1ouJziT/mYomuiZt6LrrJtOdHZNwlOErERBuyOwqeVoL3aP6pMKsLpNqNuw/jxsNpTWeaP3tDs68Y27s9TPGHYhowcV6Wx0cmbPJUDlsluMRg06BP0pf2ZVOm486qu4NpXQQiGgF3cOwUFTkvQ8ZPZ9Pb3/24FHMg6+8u2U7v1sV93Q11NTlGXlo9rU4hiL0FumLoTQMD5mn9l8QwEzC6/2Eq3HwRNuTdCyySWiLcH5GdT5oz0c0Q04v5Jh9wpnu7nF6KBFca1FE/ZE9YqJbsVOg/toVQPXBGQPKpZPlfbILlKXKbNpQpG2z/IcjsvI43DifbGGNrvmRxRWsB4="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdsutils"

    # The name of the conda package
    - CONDA_PACKAGE="pcdsutils"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda-latest.yml
