{% set data = load_setup_py_data() %}

package:
    name    : pcdsutils
    version : {{ data.get('version') }}

source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.7
      - setuptools
    run:
      - python >=3.7
      - prettytable
      - pypandoc
      - pyyaml
      - qtpyinheritance
      - requests

test:
    imports:
      - pcdsutils
      - pcdsutils.qt
    requires:
      - pytest
      - qtpy
      - pyqt

about:
  home: https://github.com/pcdshub/pcdsutils
  license: SLAC Open License
  summary: PCDS Python Utilities
