name: PCDS Standard Testing

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-standard.yml@master
    secrets: inherit
    with:
      package-name: "pcdsutils"
      # Testing extras for both conda/pip jobs:
      testing-extras: ""
      # Testing extras for just conda:
      conda-testing-extras: ""
      # Testing extras for just pip:
      pip-testing-extras: ""
      # System packages to be installed only for conda-based testing:
      conda-system-packages: ""
      # System packages to be installed only for pip-based testing:
      pip-system-packages: ""
      # System packages to be installed only for documentation:
      docs-system-packages: ""
      # Set if using setuptools-scm for the conda-build workflow
      use-setuptools-scm: true
